<script type="text/javascript" src="http://panzi.github.io/Browser-Ponies/basecfg.js"
        id="browser-ponies-config"></script>
<script type="text/javascript" src="http://panzi.github.io/Browser-Ponies/browserponies.js"
        id="browser-ponies-script"></script>
<script type="text/javascript">/* <![CDATA[ */
    (function (cfg) {
        BrowserPonies.setBaseUrl(cfg.baseurl);
        BrowserPonies.loadConfig(BrowserPoniesBaseConfig);
        BrowserPonies.loadConfig(cfg);
    })({"baseurl": "http://panzi.github.io/Browser-Ponies/", "fadeDuration": 500, "volume": 1, "fps": 25, "speed": 3, "audioEnabled": false, "showFps": false, "showLoadProgress": true, "speakProbability": 0.1, "spawnRandom": 1, "autostart": true});
    /* ]]> */</script>